spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/vlib_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: vlAdm
    password: YTMyN2E4NzJkMzNjYjU1YzczYWFmMzNh
    data: data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 5000
app:
  jwtSecret: Y2VmMzdmZTU2YmRmYzExMjkzZDYzZDVj
  jwtExpirationInMs: 604800000
